version: 2.1 

jobs: 
  build-and-test:  
    machine: 
      image: ubuntu-2004:current 
        
    steps: 
      - checkout 
      - run: echo
      - run: echo
      - run: echo

workflows: 
  basic:  
    jobs: 
      - build-and-test